#!/usr/bin/env python3
import argparse
import itertools
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pkgmeta", required=True)
    parser.add_argument("--ignore-config", required=True)
    parser.add_argument("--zip-exclude", required=True)
    parser.add_argument("--addon-folder", required=True)
    parser.add_argument("--addon-title", required=True)
    return parser.parse_args()


def load_ignore_config(path: Path):
    config = {"common": [], "zip": [], "packager": []}
    if not path.exists():
        return config
    current = None
    for raw_line in path.read_text().splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.endswith(":"):
            key = stripped[:-1].strip()
            if key:
                current = key
                config.setdefault(key, [])
            continue
        if stripped.startswith("-"):
            if current is None:
                continue
            entry = stripped[1:].strip()
            if entry:
                config.setdefault(current, []).append(entry)
    return config


def write_pkgmeta(pkgmeta_path: Path, addon_folder: str, addon_title: str, packager_entries):
    text = pkgmeta_path.read_text()
    replacements = {
        "__ADDON_FOLDER__": addon_folder,
        "__ADDON_TITLE__": addon_title,
    }
    for key, value in replacements.items():
        text = text.replace(key, value)

    if packager_entries:
        ignore_block = "\n".join(f"    - {entry}" for entry in packager_entries)
    else:
        ignore_block = "    []"
    text = text.replace("__PACKAGER_IGNORE__", ignore_block)
    pkgmeta_path.write_text(text)


def write_zip_ignore(zip_path: Path, entries):
    lines = ["# Generated by wow-addon-release-workflows"]
    lines.extend(entries)
    # Always ensure the generated file excludes itself
    if zip_path.name not in entries:
        lines.append(zip_path.name)
    zip_path.write_text("\n".join(lines) + "\n")


def main():
    args = parse_args()
    pkgmeta_path = Path(args.pkgmeta)
    ignore_config_path = Path(args.ignore_config)
    zip_exclude_path = Path(args.zip_exclude)

    config = load_ignore_config(ignore_config_path)
    common = config.get("common", [])
    zip_only = config.get("zip", [])
    packager_only = config.get("packager", [])

    zip_entries = list(itertools.chain(common, zip_only))
    packager_entries = list(itertools.chain(common, packager_only))

    write_pkgmeta(pkgmeta_path, args.addon_folder, args.addon_title, packager_entries)
    write_zip_ignore(zip_exclude_path, zip_entries)


if __name__ == "__main__":
    main()
