name: Release Addon
# Usage:
# - Copy into .github/workflows/release.yml in your addon repo.
# - Define repo variables (Settings > Secrets and variables > Actions > Variables):
#     ADDON_FOLDER: addon folder/slug (required; defaults to repo name if omitted)
#     ADDON_TITLE: display name (optional; defaults to addon folder)
# - Add provider secrets (Settings > Secrets and variables > Actions > Secrets):
#     CURSEFORGE_TOKEN, WAGO_TOKEN, WOWI_TOKEN
# - Triggers on GitHub release publish; workflow_dispatch supports skip_publish to only build the zip.
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      skip_publish:
        description: "Only create zip, don't push to addon services"
        required: false
        type: boolean
        default: false

jobs:
  release:
    permissions:
      contents: write  
    uses: PeluxGit/wow-addon-release-workflows/.github/workflows/addon-release.yml@main
    with:
      addon_folder: ${{ vars.ADDON_FOLDER || github.event.repository.name }}
      addon_title: ${{ vars.ADDON_TITLE || vars.ADDON_FOLDER || github.event.repository.name }}
      skip_publish: ${{ github.event_name == 'workflow_dispatch' && inputs.skip_publish || false }}
    secrets: inherit
